services:
  morae-mysql:
    image: mysql:8.4
    env_file:
      - ./backend/.env
    ports:
      - 3306:3306
    volumes:
      - morae-mysql_data:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost -u root -pdocker
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  morae-mysql_data: {}
