using backend.Settings;
using Microsoft.Extensions.Options;

namespace backend.Services.Storage;

public class LocalFileStorage : IFileStorage
{
    private readonly string _rootPath;

    public LocalFileStorage(IOptions<StorageSettings> options, IWebHostEnvironment environment)
    {
        var configured = options.Value.LocalPath;

        _rootPath = Path.GetFullPath(string.IsNullOrWhiteSpace(configured)
            ? Path.Combine(environment.ContentRootPath, "storage")
            : configured);

        Directory.CreateDirectory(_rootPath);
    }

    public async Task SaveAsync(string key, Stream content, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        // Written to a temporary name first, so a failed upload never leaves half a file behind.
        var temporaryPath = path + ".uploading";

        await using (var file = new FileStream(temporaryPath, FileMode.CreateNew, FileAccess.Write, FileShare.None))
        {
            await content.CopyToAsync(file, cancellationToken);
        }

        File.Move(temporaryPath, path);
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);

        Stream? stream = File.Exists(path)
            ? new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true)
            : null;

        return Task.FromResult(stream);
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);

        if (File.Exists(path))
            File.Delete(path);

        return Task.CompletedTask;
    }

    // Keys are generated by the API, but the check keeps any key from pointing outside the folder.
    private string ResolvePath(string key)
    {
        var path = Path.GetFullPath(Path.Combine(_rootPath, key));

        if (!path.StartsWith(_rootPath + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            throw new InvalidOperationException("Invalid storage key.");

        return path;
    }
}
